# Generated by Django 3.0 on 2020-12-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kid123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Sex', models.CharField(max_length=2)),
                ('Missing_Since', models.CharField(max_length=100)),
                ('Missing_From', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=30)),
                ('Height', models.IntegerField(null=True)),
                ('Weight', models.IntegerField(null=True)),
                ('Age', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid', to='adoptions.Country123')),
            ],
        ),
    ]
